#!/usr/bin/env ruby

$LOAD_PATH.unshift(
    "#{__dir__}/../lib"
)


require 'rephlex/cli'

begin
    Rephlex::CLI.start
  rescue Rephlex::CLI::Error => err
    puts "ERROR: #{err.message}"
    exit 1
  end
